[phases.install]
commands = [
  "composer install --no-dev --optimize-autoloader",
  "yarn install --frozen-lockfile"
]

[phases.build]
commands = [
  "yarn prod"
]

[phases.start]
commands = [
  "php artisan migrate --force",
  "php artisan optimize:clear",
  "php artisan storage:link"
]

[variables]
PORT = "8000"

[processes]
web = "php artisan serve --host=0.0.0.0 --port=${PORT}"
